apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-web'
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/project: '{{ .Chart.Name }}'
    app.kubernetes.io/release: '{{ .Release.Name }}'
spec:
  selector:
    app.kubernetes.io/component: web
    app.kubernetes.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      name: "http"
      port: 80
      targetPort: 5000
